//! Database access — all queries use sqlx **compile-time macros** (`query!` /
//! `query_as!` / `query_scalar!`), which type-check SQL against the schema at
//! build time. The `.sqlx/` offline cache (generated by `cargo sqlx prepare`)
//! lets Docker builds compile without a DB (`SQLX_OFFLINE=true`).

use anyhow::Result;
use sqlx::sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions, SqliteSynchronous};
use sqlx::{Pool, Sqlite};
use std::str::FromStr;

use crate::config;
use crate::models::{ArchiveRound, ArchiveSnapshot, Grilling, Response, SessionStatus};

// Re-export row types — definitions live in `models`, surfaced here for callers
// that import via `crate::db::*`.
pub use crate::models::{RoundRow, RoundSummaryRow, SessionRow};

// ---------------------------------------------------------------------------
// SQLite pragma constants
// ---------------------------------------------------------------------------

/// SQLite page cache size in pages (negative = KiB). 200 MiB.
/// Tuned for typical session workload; increase if working set grows.
const SQLITE_CACHE_SIZE: &str = "-200000";

/// SQLite mmap size in bytes. 512 MiB.
/// Enables memory-mapped I/O for read-heavy workloads.
const SQLITE_MMAP_SIZE: &str = "536870912";

/// SQLite WAL auto-checkpoint threshold in pages.
/// Default 1000 pages ~ 4 MiB; balances write throughput vs recovery time.
const SQLITE_WAL_AUTOCHECKPOINT: &str = "1000";

/// SQLite temp_store mode. MEMORY avoids disk I/O for transient sort/hash.
const SQLITE_TEMP_STORE: &str = "MEMORY";

/// SQLite extended result code for PRIMARY KEY constraint violation.
/// Used for session ID collision retry logic.
pub const SQLITE_CONSTRAINT_PRIMARYKEY: &str = "197";

/// Create and configure the SQLite connection pool.
pub async fn create_pool() -> Result<Pool<Sqlite>> {
    let opts = SqliteConnectOptions::from_str(&format!(
        "sqlite://{}?mode=rwc",
        config::settings().db_path.display()
    ))?
    .create_if_missing(true)
    .journal_mode(SqliteJournalMode::Wal)
    .synchronous(SqliteSynchronous::Normal)
    .busy_timeout(config::BUSY_TIMEOUT)
    .foreign_keys(true)
    .pragma("cache_size", SQLITE_CACHE_SIZE)
    .pragma("mmap_size", SQLITE_MMAP_SIZE)
    .pragma("wal_autocheckpoint", SQLITE_WAL_AUTOCHECKPOINT)
    .pragma("temp_store", SQLITE_TEMP_STORE);

    let pool = SqlitePoolOptions::new()
        .max_connections(config::DB_POOL_MAX)
        .min_connections(config::DB_POOL_MIN)
        .acquire_timeout(config::ACQUIRE_TIMEOUT)
        .connect_with(opts)
        .await?;

    Ok(pool)
}

/// Run database migrations.
pub async fn run_migrations(pool: &Pool<Sqlite>) -> Result<()> {
    sqlx::migrate!("./migrations").run(pool).await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Session CRUD
// ---------------------------------------------------------------------------

/// Insert a new session with its first round. Returns the first round's id.
///
/// Order: insert the session row first (curr_round NULL), then the first round
/// (its session_id FK is now satisfied), then set curr_round to the new round
/// id. The FK `rounds.session_id → sessions.id` requires sessions to exist
/// first; curr_round → rounds.id is set after the round exists.
pub async fn create_session(
    pool: &Pool<Sqlite>,
    session_id: &str,
    grilling: &Grilling,
    created_at: i64,
    expires_at: i64,
) -> Result<i64> {
    let mut tx = pool.begin().await?;

    let grilling_json = serde_json::to_string(grilling)?;

    // Insert session (curr_round NULL initially).
    sqlx::query!(
        "INSERT INTO sessions (id, status, curr_round, name, created_at, expires_at)
         VALUES (?, 0, NULL, ?, ?, ?)",
        session_id,
        grilling.name,
        created_at,
        expires_at,
    )
    .execute(&mut *tx)
    .await?;

    // Insert first round (FK to sessions satisfied). RETURNING id is always
    // present, but sqlx types it as Option<i64> — unwrap is safe here.
    let row_id = sqlx::query_scalar!(
        "INSERT INTO rounds (session_id, seq, name, grilling, created_at)
         VALUES (?, 1, ?, ?, ?)
         RETURNING id",
        session_id,
        grilling.name,
        grilling_json,
        created_at,
    )
    .fetch_one(&mut *tx)
    .await?
    .expect("RETURNING id must be present");

    // Set the curr_round pointer to the new round.
    sqlx::query!(
        "UPDATE sessions SET curr_round = ? WHERE id = ?",
        row_id,
        session_id
    )
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;
    Ok(row_id)
}

/// Get session status and metadata. Returns None if not found.
pub async fn get_session(pool: &Pool<Sqlite>, session_id: &str) -> Result<Option<SessionRow>> {
    // `id as "id!"` overrides sqlx's nullable inference for TEXT PRIMARY KEY
    // (SQLite only treats INTEGER PRIMARY KEY as implicitly NOT NULL).
    let row = sqlx::query_as!(
        SessionRow,
        r#"SELECT id as "id!", status, curr_round, name, created_at, expires_at,
                cancel_reason, cancel_detail, cancel_actor
         FROM sessions WHERE id = ?"#,
        session_id
    )
    .fetch_optional(pool)
    .await?;

    Ok(row)
}

/// Get session by ID, returning Gone if in terminal state.
///
/// DESIGN.md §319-333: GET /sessions/{id} distinguishes "never existed" (404)
/// from "existed but archived" (410). After a terminal transition the session
/// row is moved to `session_archive`, so a 410 requires falling back to the
/// archive table to recover the terminal status.
pub async fn get_session_or_gone(
    pool: &Pool<Sqlite>,
    session_id: &str,
) -> Result<SessionRow, crate::error::ApiError> {
    if let Some(row) = get_session(pool, session_id).await? {
        let status = SessionStatus::try_from(row.status).unwrap_or(SessionStatus::Expired);
        if status.is_terminal() {
            return Err(crate::error::ApiError::Gone {
                detail: status.terminal_detail().to_string(),
            });
        }
        return Ok(row);
    }

    // Fall back to archive.
    if let Some((status_int, _reason)) = get_archive_status(pool, session_id).await? {
        let status = SessionStatus::try_from(status_int).unwrap_or(SessionStatus::Expired);
        return Err(crate::error::ApiError::Gone {
            detail: status.terminal_detail().to_string(),
        });
    }

    Err(crate::error::ApiError::NotFound)
}

/// Update session status (completed or cancelled). Returns rows affected.
pub async fn update_session_status(
    pool: &Pool<Sqlite>,
    session_id: &str,
    status: SessionStatus,
    cancel_reason: Option<&str>,
    cancel_detail: Option<&str>,
    cancel_actor: Option<&str>,
) -> Result<u64> {
    let result = sqlx::query!(
        "UPDATE sessions SET status = ?, cancel_reason = ?, cancel_detail = ?, cancel_actor = ?
         WHERE id = ? AND status = 0",
        status as i64,
        cancel_reason,
        cancel_detail,
        cancel_actor,
        session_id,
    )
    .execute(pool)
    .await?;

    Ok(result.rows_affected())
}

// ---------------------------------------------------------------------------
// Round CRUD
// ---------------------------------------------------------------------------

/// Create a new round. Returns (seq, id).
pub async fn create_round(
    pool: &Pool<Sqlite>,
    session_id: &str,
    grilling: &Grilling,
    created_at: i64,
) -> Result<(i64, i64)> {
    let mut tx = pool.begin().await?;

    let max_seq: Option<i64> = sqlx::query_scalar!(
        "SELECT MAX(seq) FROM rounds WHERE session_id = ?",
        session_id
    )
    .fetch_one(&mut *tx)
    .await?;

    let new_seq = max_seq.unwrap_or(0) + 1;
    let grilling_json = serde_json::to_string(grilling)?;

    let round_id = sqlx::query_scalar!(
        "INSERT INTO rounds (session_id, seq, name, grilling, created_at)
         VALUES (?, ?, ?, ?, ?)
         RETURNING id",
        session_id,
        new_seq,
        grilling.name,
        grilling_json,
        created_at,
    )
    .fetch_one(&mut *tx)
    .await?
    .expect("RETURNING id must be present");

    sqlx::query!(
        "UPDATE sessions SET curr_round = ? WHERE id = ?",
        round_id,
        session_id
    )
    .execute(&mut *tx)
    .await?;

    tx.commit().await?;
    Ok((new_seq, round_id))
}

/// Get the current round for a session.
pub async fn get_current_round(pool: &Pool<Sqlite>, session_id: &str) -> Result<Option<RoundRow>> {
    let row = sqlx::query_as!(
        RoundRow,
        "SELECT r.id, r.session_id, r.seq, r.name, r.grilling, r.response, r.created_at
         FROM rounds r
         JOIN sessions s ON s.curr_round = r.id
         WHERE s.id = ?",
        session_id
    )
    .fetch_optional(pool)
    .await?;

    Ok(row)
}

/// Get a round by session_id and seq.
pub async fn get_round(
    pool: &Pool<Sqlite>,
    session_id: &str,
    seq: i64,
) -> Result<Option<RoundRow>> {
    let row = sqlx::query_as!(
        RoundRow,
        "SELECT id, session_id, seq, name, grilling, response, created_at
         FROM rounds WHERE session_id = ? AND seq = ?",
        session_id,
        seq,
    )
    .fetch_optional(pool)
    .await?;

    Ok(row)
}

/// List all rounds for a session (summary).
pub async fn list_rounds(pool: &Pool<Sqlite>, session_id: &str) -> Result<Vec<RoundSummaryRow>> {
    let rows = sqlx::query_as!(
        RoundSummaryRow,
        "SELECT seq, name, response IS NOT NULL AS has_response
         FROM rounds WHERE session_id = ? ORDER BY seq",
        session_id
    )
    .fetch_all(pool)
    .await?;

    Ok(rows)
}

/// Get a round by its physical ID (curr_round lookup).
pub async fn get_round_by_id(pool: &Pool<Sqlite>, round_id: i64) -> Result<Option<RoundRow>> {
    let row = sqlx::query_as!(
        RoundRow,
        "SELECT id, session_id, seq, name, grilling, response, created_at
         FROM rounds WHERE id = ?",
        round_id
    )
    .fetch_optional(pool)
    .await?;

    Ok(row)
}

/// Check if a round exists.
pub async fn round_exists(pool: &Pool<Sqlite>, session_id: &str, seq: i64) -> Result<bool> {
    let exists: i64 = sqlx::query_scalar!(
        "SELECT EXISTS(SELECT 1 FROM rounds WHERE session_id = ? AND seq = ?)",
        session_id,
        seq
    )
    .fetch_one(pool)
    .await?;
    Ok(exists != 0)
}

// ---------------------------------------------------------------------------
// Response CRUD
// ---------------------------------------------------------------------------

/// Submit a response. Returns Ok(true) if first submission, Ok(false) if
/// already submitted (concurrent conflict).
pub async fn submit_response(
    pool: &Pool<Sqlite>,
    session_id: &str,
    seq: i64,
    response_json: &str,
) -> Result<bool> {
    let result = sqlx::query!(
        "UPDATE rounds SET response = ? WHERE session_id = ? AND seq = ? AND response IS NULL",
        response_json,
        session_id,
        seq,
    )
    .execute(pool)
    .await?;
    Ok(result.rows_affected() == 1)
}

/// Get the response for a round. Ok(None) if no response yet or round absent.
pub async fn get_response(
    pool: &Pool<Sqlite>,
    session_id: &str,
    seq: i64,
) -> Result<Option<String>> {
    let row = sqlx::query_scalar!(
        "SELECT response FROM rounds WHERE session_id = ? AND seq = ?",
        session_id,
        seq
    )
    .fetch_optional(pool)
    .await?;
    // response is nullable: fetch_optional returns Option<Option<String>>;
    // outer None = no row, inner None = NULL. Flatten.
    Ok(row.flatten())
}

// ---------------------------------------------------------------------------
// Archive
// ---------------------------------------------------------------------------

/// Archive a session and all its rounds. Returns Ok(true) if archived,
/// Ok(false) if already gone (no-op).
pub async fn archive_session(
    pool: &Pool<Sqlite>,
    session_id: &str,
    status: SessionStatus,
    now: i64,
) -> Result<bool> {
    // Reuse get_session to avoid duplicating the session SELECT query.
    // The lookup is outside the transaction (session archiving is infrequent;
    // a concurrent archive between this check and the INSERT below is harmless
    // — the INSERT will simply find the session already deleted).
    let session = match get_session(pool, session_id).await? {
        Some(s) => s,
        None => return Ok(false),
    };

    let mut tx = pool.begin().await?;

    let rounds = sqlx::query_as!(
        RoundRow,
        "SELECT id, session_id, seq, name, grilling, response, created_at
         FROM rounds WHERE session_id = ? ORDER BY seq",
        session_id
    )
    .fetch_all(&mut *tx)
    .await?;

    let total_rounds = rounds.len() as i64;
    let snapshot = ArchiveSnapshot {
        rounds: rounds
            .iter()
            .map(|r| ArchiveRound {
                seq: r.seq,
                name: r.name.clone(),
                grilling: r.grilling.clone(),
                response: r.response.clone(),
                created_at: r.created_at,
            })
            .collect(),
    };
    let snapshot_json = serde_json::to_string(&snapshot)?;

    sqlx::query!(
        "INSERT INTO session_archive
         (id, status, name, cancel_reason, cancel_detail, cancel_actor, total_rounds, created_at, archived_at, snapshot)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        session_id,
        status as i64,
        session.name,
        session.cancel_reason,
        session.cancel_detail,
        session.cancel_actor,
        total_rounds,
        session.created_at,
        now,
        snapshot_json,
    )
    .execute(&mut *tx)
    .await?;

    sqlx::query!("DELETE FROM sessions WHERE id = ?", session_id)
        .execute(&mut *tx)
        .await?;

    tx.commit().await?;
    Ok(true)
}

/// Extract non-null session IDs from sqlx query rows.
///
/// `id` is `TEXT NOT NULL` in the schema, but sqlx infers `Option<String>`
/// because SQLite only makes `INTEGER PRIMARY KEY` implicitly NOT NULL.
/// The `expect` documents this schema invariant — if the schema changes,
/// this is the single place to update.
///
/// Compare `get_session` which uses `id as "id!"` for the same reason;
/// different SQL here requires the macro approach for offline cache compat.
macro_rules! collect_session_ids {
    ($rows:expr) => {
        $rows
            .into_iter()
            .map(|r| r.id.expect("session id is NOT NULL per schema constraint"))
            .collect::<Vec<_>>()
    };
}

/// Find expired sessions (status=0 and expires_at < now).
pub async fn find_expired_sessions(pool: &Pool<Sqlite>, now: i64) -> Result<Vec<String>> {
    let rows = sqlx::query!(
        "SELECT id FROM sessions WHERE status = 0 AND expires_at < ?",
        now
    )
    .fetch_all(pool)
    .await?;
    Ok(collect_session_ids!(rows))
}

/// Find all active sessions for crash recovery.
pub async fn find_active_sessions(pool: &Pool<Sqlite>, now: i64) -> Result<Vec<String>> {
    let rows = sqlx::query!(
        "SELECT id FROM sessions WHERE status = 0 AND expires_at > ?",
        now
    )
    .fetch_all(pool)
    .await?;
    Ok(collect_session_ids!(rows))
}

/// Look up a session's terminal status (+ cancel_reason) in the archive.
pub async fn get_archive_status(
    pool: &Pool<Sqlite>,
    session_id: &str,
) -> Result<Option<(i64, Option<String>)>> {
    let row = sqlx::query!(
        "SELECT status, cancel_reason FROM session_archive WHERE id = ?",
        session_id
    )
    .fetch_optional(pool)
    .await?;
    Ok(row.map(|r| (r.status, r.cancel_reason)))
}

// ---------------------------------------------------------------------------
// Row deserialization helpers
// ---------------------------------------------------------------------------

/// Deserialize a stored grilling JSON string into a [`Grilling`].
///
/// Centralises the repeated `serde_json::from_str` + error wrapping found in
/// round/response handlers.
pub fn deserialize_grilling(json: &str) -> Result<Grilling> {
    Ok(serde_json::from_str(json)?)
}

/// Deserialize an optional stored response JSON string.
pub fn response_or_none(json: Option<&str>) -> Option<Response> {
    json.and_then(|r| serde_json::from_str(r).ok())
}
